import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/Sidebar'
import GlobalState from '@/context/context'
import Notifications from '@/components/Notifications'
import Auth from '@/components/Auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  if (typeof window !== 'undefined') {
    let loggedIn: any = window.localStorage.getItem('isLoggedIn')
    if (loggedIn === true || 'true') {

    }
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <div className='w-full h-full flex bg-white'>
            <Sidebar />
            <div className='content w-full h-full bg-white'>
              {children}
            </div>
          </div>
          {/* <Auth /> */}
        </GlobalState>
      </body>
    </html>
  )
}
